RUGBY_LEAGUES = [
    {
        "tsdb_league_id": 4446,
        "code": "urc",
        "name": "United Rugby Championship",
        "group": "division1",
        "notes": "Top club league: Ireland, Wales, Scotland, Italy, South Africa.",
    },
    {
        "tsdb_league_id": 5370,
        "code": "commonwealth_7s",
        "name": "Commonwealth Games 7s Rugby",
        "group": "division1",
        "notes": "Multi-sport games sevens rugby tournament.",
    },
    {
        "tsdb_league_id": 5069,
        "code": "currie_cup",
        "name": "Currie Cup",
        "group": "division1",
        "notes": "South African domestic competition.",
    },
    {
        "tsdb_league_id": 5166,
        "code": "premier_15s",
        "name": "English Premier 15s",
        "group": "division1",
        "notes": "Top-tier English women's club league.",
    },
    {
        "tsdb_league_id": 5167,
        "code": "japan_league_one",
        "name": "Japan Rugby League One",
        "group": "division1",
        "notes": "Top rugby union league in Japan.",
    },
    {
        "tsdb_league_id": 5070,
        "code": "mlr",
        "name": "Major League Rugby",
        "group": "division1",
        "notes": "North American professional rugby.",
    },
    {
        "tsdb_league_id": 5168,
        "code": "romanian_superliga",
        "name": "Romanian SuperLiga",
        "group": "division1",
        "notes": "Romanian domestic club rugby.",
    },
    {
        "tsdb_league_id": 5480,
        "code": "club_friendlies",
        "name": "Rugby Union Club Friendlies",
        "group": "division1",
        "notes": "Friendly club matches.",
    },
    {
        "tsdb_league_id": 5479,
        "code": "intl_friendlies",
        "name": "Rugby Union International Friendlies",
        "group": "division1",
        "notes": "Non-test friendlies between international sides.",
    },
    {
        "tsdb_league_id": 5170,
        "code": "spanish_honor",
        "name": "Spanish División de Honor",
        "group": "division1",
        "notes": "Top Spanish club competition.",
    },
    {
        "tsdb_league_id": 5169,
        "code": "sl_americana",
        "name": "Super Liga Americana",
        "group": "division1",
        "notes": "South American regional league.",
    },
    {
        "tsdb_league_id": 5701,
        "code": "super_rugby_au",
        "name": "Super Rugby Aus",
        "group": "division1",
        "notes": "Australian Super Rugby.",
    },
    {
        "tsdb_league_id": 5165,
        "code": "urba_top_13",
        "name": "URBA Top 13",
        "group": "division1",
        "notes": "Top Buenos Aires amateur/club competition.",
    },

    # ----- International / cross-border tournaments -----------------------
    {
        "tsdb_league_id": 5512,
        "code": "b_i_lions",
        "name": "British and Irish Lions Tours",
        "group": "international",
        "notes": "Lions tours vs SANZAAR nations, etc.",
    },
    {
        "tsdb_league_id": 5695,
        "code": "prem_rugby_cup",
        "name": "English Prem Rugby Cup",
        "group": "international",
        "notes": "Cup competition involving English clubs.",
    },
    {
        "tsdb_league_id": 5418,
        "code": "challenge_cup",
        "name": "European Rugby Challenge Cup",
        "group": "international",
        "notes": "Tier 2 European club competition.",
    },
    {
        "tsdb_league_id": 4550,
        "code": "champions_cup",
        "name": "European Rugby Champions Cup",
        "group": "international",
        "notes": "Top European club competition.",
    },
    {
        "tsdb_league_id": 5037,
        "code": "olympics_7s",
        "name": "Olympics 7s Rugby",
        "group": "international",
        "notes": "Olympic rugby sevens tournament.",
    },
    {
        "tsdb_league_id": 4985,
        "code": "pacific_nations",
        "name": "Pacific Nations Cup",
        "group": "international",
        "notes": "International tournament (Pacific nations).",
    },
    {
        "tsdb_league_id": 4986,
        "code": "rugby_championship",
        "name": "Rugby Championship",
        "group": "international",
        "notes": "SANZAAR + Argentina test competition.",
    },
    {
        "tsdb_league_id": 4983,
        "code": "rugby_europe_champ",
        "name": "Rugby Europe Championship",
        "group": "international",
        "notes": "European international competition below Six Nations.",
    },
    {
        "tsdb_league_id": 4574,
        "code": "rugby_world_cup",
        "name": "Rugby World Cup",
        "group": "international",
        "notes": "Men's XVs World Cup.",
    },
    {
        "tsdb_league_id": 4714,
        "code": "six_nations",
        "name": "Six Nations Championship",
        "group": "international",
        "notes": "Men's Six Nations.",
    },
    {
        "tsdb_league_id": 5082,
        "code": "six_nations_u20",
        "name": "Six Nations Under 20s",
        "group": "international",
        "notes": "U20 Six Nations.",
    },
    {
        "tsdb_league_id": 5563,
        "code": "six_nations_women",
        "name": "Six Nations Women",
        "group": "international",
        "notes": "Women's Six Nations.",
    },
    {
        "tsdb_league_id": 5682,
        "code": "womens_rwc",
        "name": "Womens Rugby World Cup",
        "group": "international",
        "notes": "Women's XVs World Cup.",
    },
]
